### ISSUE TITLE
Error on run: TypeError: (0 , _stream.finished) is not a function

### ISSUE THREAD

**Issue by markwestcott34** [planarnetwork/gtfsmerge#1]
I'm trying to run this (installed with npm repository) but receive the following output. Any clues? Thanks for developing this!

```
Loading gb-rail-latest.zip
TypeError: (0 , _stream.finished) is not a function
    at exports.default (/usr/local/lib/node_modules/gtfsmerge/node_modules/gtfs-stream/dist/plain/index.js:71:24)
    at GTFSLoader.exports.gtfsStreamFactory [as gtfsStream] (/usr/local/lib/node_modules/gtfsmerge/dist/gtfs/GTFSLoader.js:115:35)
    at resolve (/usr/local/lib/node_modules/gtfsmerge/dist/gtfs/GTFSLoader.js:17:28)
    at new Promise (<anonymous>)
    at GTFSLoader.load (/usr/local/lib/node_modules/gtfsmerge/dist/gtfs/GTFSLoader.js:15:16)
    at MergeCommand.run (/usr/local/lib/node_modules/gtfsmerge/dist/gtfs/MergeCommand.js:21:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/gtfsmerge/dist/index.js:17:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gtfsmerge/bin/gtfsmerge.sh:3:1)
    at Module._compile (module.js:652:30)
```

**Comment by linusnorton** [comment]
Hi @markwestcott34 - sorry for the slow response. What command are you running?
